"""
报告保存工具

提供超参数搜索结果的保存功能，支持JSON和Markdown格式。
"""

import json
from pathlib import Path
from typing import Union


def save_optuna_results(results: dict, output_dir: Union[str, Path]):
    """
    保存Optuna搜索结果为JSON和Markdown格式。
    
    Args:
        results: 搜索结果字典，需包含以下键：
            - search_info: 搜索配置信息
            - dataset_info: 数据集信息
            - best_params: 最佳超参数
            - best_performance: 最佳性能指标
            - study_statistics: 研究统计信息
        output_dir: 输出目录路径
        
    Returns:
        tuple: (json_path, md_path) 保存的文件路径
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(exist_ok=True, parents=True)
    
    # 保存JSON
    json_path = output_dir / "optuna_best_config.json"
    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(results, f, indent=2, ensure_ascii=False)
    
    # 生成Markdown报告
    md_path = output_dir / "optuna_search_report.md"
    md_content = _generate_markdown_report(results)
    
    with open(md_path, 'w', encoding='utf-8') as f:
        f.write(md_content)
    
    return json_path, md_path


def _generate_markdown_report(results: dict) -> str:
    """
    生成Markdown格式的搜索报告。
    
    Args:
        results: 搜索结果字典
        
    Returns:
        str: Markdown格式的报告内容
    """
    # 获取参数，兼容新旧格式
    best_params = results['best_params']
    search_info = results['search_info']
    
    # 格式化层维度
    gat_dims_str = ' -> '.join(map(str, best_params.get('gat_dims', [])))
    mlp_dims_str = ' -> '.join(map(str, best_params.get('mlp_dims', [])))
    num_gat_layers = len(best_params.get('gat_dims', []))
    num_mlp_layers = len(best_params.get('mlp_dims', []))
    
    # 获取基础倍率信息
    base_unit = search_info.get('base_unit', 16)
    multiplier_range = search_info.get('multiplier_range', [1, 8])
    
    # 获取模型参数量
    model_params = results.get('study_statistics', {}).get('model_parameters', 'N/A')
    if isinstance(model_params, int):
        model_params = f"{model_params:,}"
    
    return f"""# Optuna GNN Hyperparameter Search Report

## Search Information

| Parameter | Value |
|-----------|-------|
| Number of Trials | {search_info['n_trials']} |
| Epochs per Trial | {search_info['num_epochs_per_trial']} |
| Early Stopping Patience | {search_info['patience']} |
| Batch Size | {search_info['batch_size']} |
| Random Seed | {search_info['random_seed']} |
| Base Unit | {base_unit} |
| Multiplier Range | {multiplier_range[0]} - {multiplier_range[1]} |
| Timestamp | {search_info['timestamp']} |

## Dataset Information

| Parameter | Value |
|-----------|-------|
| Total Samples | {results['dataset_info']['total_samples']} |
| Training Samples | {results['dataset_info']['train_samples']} (70%) |
| Validation Samples | {results['dataset_info']['val_samples']} (15%) |
| Test Samples | {results['dataset_info']['test_samples']} (15%) |
| Node Features | {results['dataset_info']['num_node_features']} |
| Edge Features | {results['dataset_info']['num_edge_features']} |
| Global Features | {results['dataset_info']['num_global_features']} |

## Best Model Architecture

### Network Structure

| Parameter | Value |
|-----------|-------|
| GAT Layers | {num_gat_layers} |
| GAT Dimensions | {gat_dims_str} |
| MLP Layers | {num_mlp_layers} |
| MLP Dimensions | {mlp_dims_str} |
| Attention Heads | {best_params['num_heads']} |
| Dropout Rate | {best_params['dropout']} |
| Total Parameters | {model_params} |

### Training Hyperparameters

| Parameter | Value |
|-----------|-------|
| Learning Rate | {best_params['lr']:.6f} |
| Weight Decay | {best_params['weight_decay']:.6f} |

## Performance

### Validation Set (used for optimization)

| Metric | Value |
|--------|-------|
| MAE | {results['best_performance']['val_mae']:.4f} |

### Test Set (final evaluation)

| Metric | Value |
|--------|-------|
| R2 | {results['best_performance']['test_r2']:.4f} |
| MAE | {results['best_performance']['test_mae']:.4f} |
| RMSE | {results['best_performance']['test_rmse']:.4f} |

## Study Statistics

| Metric | Value |
|--------|-------|
| Completed Trials | {results['study_statistics']['n_completed_trials']} |
| Pruned Trials | {results['study_statistics']['n_pruned_trials']} |

---

*Report generated by optuna_gnn_framework.py*
"""
